### ISSUE TITLE
environment.yml file incorrect

### ISSUE THREAD

**Issue by v-rico-ms** [microsoft/datadrivenmodel#11]
It appears that one or more requirements in this file may need to be updated. For example, YAML is one of those. The current requested file/version is not available. I believe that pyyaml is the intended library as it has the 'full_load' method.

![image](https://user-images.githubusercontent.com/63866229/98390263-fad52800-2009-11eb-9818-9fb0dc92d1d0.png)

**Comment by journeyman-msft** [comment]
@v-rico-ms Good catch, #14 should fix that.
