### ISSUE TITLE
Default data driven model - Predictor fails

### ISSUE THREAD

**Issue by v-rico-ms** [microsoft/datadrivenmodel#12]
When an Event.Start is received, the code is executed and the registered simulator fails because of 'theta'. The predictor state is reset, and in that function, where the dictionary is being updated, the code fails as shown below:

![image](https://user-images.githubusercontent.com/63866229/98390896-d2016280-200a-11eb-8ffd-816dcae35bac.png)
![image](https://user-images.githubusercontent.com/63866229/98390929-d9287080-200a-11eb-8085-148affb0e52b.png)

**Comment by akzaidi** [comment]
have you updated `config_model.yml`?
