### ISSUE TITLE
[BUG] ddm_predictor.py type mismatch when concatenating columns

### ISSUE THREAD

**Issue by xiaolul** [microsoft/datadrivenmodel#49]
When trying to running the following command

`python ddm_predictor.py simulator=cartpole_simparam`

An error occurs:
```
Traceback (most recent call last):
  File "ddm_predictor.py", line 383, in main
    input_cols = input_cols + augmented_cols
TypeError: can only concatenate str (not "list") to str
```

When looking at the `input_cols`, in the config file, it is a prefix string "state", here we are concatenating string and list.
Also, since it is predictor, there is no data loading hence nowhere to get the correct column names.

Am I missing something, or this is a bug that either:
- We specify the column names in the config file using full name or
- We update the predictor to let it obtain column names

**Comment by mzat-msft** [comment]
I cannot reproduce the issue with the current version. Do you still experience this? If yes, please reopen the issue.
